#!/usr/bin/env node

var cli = require('./lib')
  , optimist = require('optimist');

var commandArguments = optimist.argv._;

cli.execute(optimist.argv, function(err) {
    if (err) return console.log('command failed: ' + err);

    process.exit(0);
});