#!/usr/bin/env node

var cli = require('./lib')
  , optimist = require('optimist');

var commandArguments = optimist.argv._;

cli.execute(optimist.argv, function(err) {
    if (err) return cli.log.error(JSON.stringify(err));

    process.exit(0);
});